Repository ftinx/webserv, pull requests merged in 2021-02, with the labels that each got.

#1 [FEAT] add coding convention.md
  convention.md
Labels: 10 minute task

#9 [FEAT] create config hpp #4
  includes/HttpConfig.hpp
  includes/HttpConfigLocation.hpp
  includes/HttpConfigServer.hpp
Labels: 10 minute task

#16 [FEAT] add request hpp #2
  includes/Request.hpp
Labels: 10 minute task

#23 [FEAT] create Server.hpp #13
  convention.md
  includes/Server.hpp
Labels: Server

#33 [Server] select 구현
  .vscode/settings.json
  Makefile
  includes/HttpConfig.hpp
  includes/HttpConfigLocation.hpp
  includes/HttpConfigServer.hpp
  includes/Request.hpp
  includes/Response.hpp
  includes/Server.hpp
  includes/ServerManager.hpp
  includes/utils.hpp
  srcs/Server.cpp
  srcs/main.cpp
  srcs/utils.cpp
Labels: 30 minute task, Server
